# Generated by Django 2.2.2 on 2019-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fullname', models.CharField(max_length=25)),
                ('Tel_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
